#!/bin/bash

echo "=== BYGGSKRIPT FÖR VÄDERSYSTEMET ==="
echo ""
echo "OBSERVERA: Detta projekt kräver GCC och Make för att byggas."
echo ""
echo "Du har två alternativ:"
echo ""
echo "1. Installera WSL (Windows Subsystem for Linux):"
echo "   - Öppna PowerShell som Administrator"
echo "   - Kör: wsl --install"
echo "   - Starta om datorn"
echo "   - Efter omstart, öppna WSL och kör:"
echo "     cd /mnt/c/Users/moham/Downloads/mohammed/vädersystem"
echo "     make run"
echo ""
echo "2. Installera MinGW-w64:"
echo "   - Ladda ner från: https://www.mingw-w64.org/"
echo "   - Installera och lägg till i PATH"
echo "   - Kör sedan: make run"
echo ""
echo "3. Använd Visual Studio med MSVC:"
echo "   - Installera Visual Studio med C++ Desktop Development"
echo "   - Kompilera manuellt med cl.exe"
echo ""
echo "=== MANUELL KOMPILERING (om du har en C-kompilator) ==="
echo ""
echo "Om du har gcc installerat, kör följande kommandon:"
echo ""
echo "cd Server"
echo "gcc -Wall -Wextra -I../libs -g -o weather_server main.c ../libs/TCP.c ../libs/HTTP.c ../libs/cache.c"
echo "./weather_server"
echo ""
